{
 "title": "Web logs dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Top users by request count",
   "type": "table",
   "description": "Топ-10 пользователей по количеству запросов",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n    user_id,\n    count() as requests_count\nfrom web_logs\ngroup by user_id\norder by requests_count desc\nlimit 10;\n"
    }
   ]
  },
  {
   "title": "Count of errors",
   "type": "table",
   "description": "Общее число ошибок",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n    countIf(status_code between 400 and 499) as client_errors,\n    countIf(status_code between 500 and 599) as server_errors\nfrom web_logs;\n"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "table",
   "description": "Среднее время ответа для каждого URL",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select\n  replaceRegexpAll(url, '/\\d+', '/{id}') as url,\n  avg(response_time) as average_response_time\nfrom web_logs\ngroup by url\norder by average_response_time desc\nlimit 5;\n"
    }
   ]
  },
  {
   "title": "Requests per day",
   "type": "timeseries",
   "description": "Запросы за день",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "select\n  toDate(timestamp) as day,\n  count()\nfrom web_logs\ngroup by day\norder by day asc;\n"
    }
   ]
  }
 ]
}